### ISSUE TITLE
Internal black padding in gtk3 applications

### ISSUE THREAD

**Issue by PaBLoX-CL** [baskerville/bspwm#238]
Since a couple of weeks I've been noticing this strange behaviour with gtk3 applications (evince, nautilus, ecc).

![recent documents_001](https://cloud.githubusercontent.com/assets/275754/7339712/3360e60e-ec4f-11e4-921d-a87262101e76.png)

I'm not using any kind of composition manager. Any idea what could be causing this?
```
~ ❯❯❯ pacman -Qi bspwm-git
Name           : bspwm-git
Version        : 993-1
```

**Comment by PaBLoX-CL** [comment]
Sorry the noise, after posting this I found the solution in the Arch Wiki [bspwm page](https://wiki.archlinux.org/index.php/Bspwm#Window_box_larger_than_the_actual_application.21)

If someone find this first, the solution is simple:

```css
/* ~/.config/gtk-3.0/gtk.css */
.window-frame, .window-frame:backdrop {
  box-shadow: 0 0 0 black;
  border-style: none;
  margin: 0;
  border-radius: 0;
}
    
.titlebar {
  border-radius: 0;
}
```
